"""Generate the app icons committed under web/static/ from docs/assets/logo.svg.

docs/assets/logo.svg holds the only hand-authored geometry. This script wraps
it in the two container forms and rasterises them:

  icon.svg           rounded square (18% radius) — manifest `purpose: any`
  icon-maskable.svg  full-bleed square — manifest `purpose: maskable`. Android
                     applies its own mask, so this one must not be pre-rounded
                     and the mark must stay inside the central 80%.
  logo-on-dark.svg   bare mark, cyan — README <picture>, dark GitHub theme
  logo-on-light.svg  bare mark, deep teal — README <picture>, light theme

Both containers put the cyan mark (--primary: #22d3ee) on graphite
(--bg: #0b0c0f) rather than shipping a bare mark: cyan on white is only
1.8:1, which is unreadable on a light browser tab strip.

The bare mark is also copied to web/static/logo.svg, where the UI uses it as a
CSS mask so the mark follows --primary across the light and dark themes.

Requires librsvg for rsvg-convert (`brew install librsvg`), in the same spirit
as scripts/readme_assets/render.sh requiring Chrome. All outputs are committed,
so only a maintainer regenerating the icons needs it.

Usage: python scripts/gen_pwa_icons.py
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOGO = ROOT / "docs" / "assets" / "logo.svg"
ASSETS = ROOT / "docs" / "assets"
STATIC = ROOT / "web" / "static"
ICONS = STATIC / "icons"

PRIMARY = "#22d3ee"  # --primary (dark theme) in web/src/app.css
PRIMARY_LIGHT = "#0e7490"  # --primary (light theme); 5.4:1 on white
BG = "#0b0c0f"  # --bg (dark theme) in web/src/app.css

CANVAS = 64  # container viewBox side; PNG sizes scale from here
CORNER_RADIUS_RATIO = 0.18

# Mark width as a fraction of the canvas. The maskable icon is capped by the
# safe zone: the mark's bbox corner sits at 1.1789 * (ratio * CANVAS / 2) from
# the centre, which must stay inside the central 80% circle, so ratio <= 0.678.
# The `any` icon is never masked, so it crops tighter for small-size legibility.
MARK_WIDTH_RATIO_ANY = 0.75
MARK_WIDTH_RATIO_MASKABLE = 0.65


def _mark_body(colour: str = PRIMARY) -> tuple[str, float, float]:
    """Inner markup of logo.svg plus its viewBox size, with colour resolved."""
    svg = LOGO.read_text(encoding="utf-8")
    view_box = re.search(r'viewBox="0 0 ([\d.]+) ([\d.]+)"', svg)
    body = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S)
    if not view_box or not body:
        raise SystemExit(f"cannot parse {LOGO}")
    inner = body.group(1).strip().replace("currentColor", colour)
    return inner, float(view_box.group(1)), float(view_box.group(2))


def _tinted_svg(colour: str) -> str:
    """Bare mark with the colour baked in, for contexts that cannot supply one.

    The READMEs embed these through a <picture> element: GitHub renders images
    with <img>, where currentColor would resolve to black on both themes.
    """
    inner, mark_w, mark_h = _mark_body(colour)
    return (
        "<!-- Generated by scripts/gen_pwa_icons.py from docs/assets/logo.svg."
        " Do not edit. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {mark_w:g} {mark_h:g}"'
        f' width="{mark_w:g}" height="{mark_h:g}" fill="none">\n'
        f"  {inner}\n"
        "</svg>\n"
    )


def _container_svg(rounded: bool) -> str:
    inner, mark_w, mark_h = _mark_body()
    ratio = MARK_WIDTH_RATIO_ANY if rounded else MARK_WIDTH_RATIO_MASKABLE
    scale = CANVAS * ratio / mark_w
    tx = (CANVAS - mark_w * scale) / 2
    ty = (CANVAS - mark_h * scale) / 2
    radius = CANVAS * CORNER_RADIUS_RATIO if rounded else 0
    return (
        "<!-- Generated by scripts/gen_pwa_icons.py from docs/assets/logo.svg."
        " Do not edit. -->\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {CANVAS} {CANVAS}"'
        f' width="{CANVAS}" height="{CANVAS}" fill="none">\n'
        f'  <rect width="{CANVAS}" height="{CANVAS}" rx="{radius:g}" fill="{BG}"/>\n'
        f'  <g transform="translate({tx:g},{ty:g}) scale({scale:g})">\n'
        f"    {inner}\n"
        "  </g>\n"
        "</svg>\n"
    )


def rasterise(svg: Path, size: int, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), str(svg), "-o", str(out)],
        check=True,
    )
    print(f"wrote {out.relative_to(ROOT)} ({size}x{size})")


def main() -> None:
    # logo.svg is shipped to the browser as a CSS mask, so it has to be valid
    # XML — an XML comment may not contain a double hyphen, which is easy to
    # trip over when documenting CSS custom properties in the header.
    subprocess.run(["rsvg-convert", str(LOGO)], check=True, stdout=subprocess.DEVNULL)

    icon = ASSETS / "icon.svg"
    maskable = ASSETS / "icon-maskable.svg"
    icon.write_text(_container_svg(rounded=True), encoding="utf-8")
    maskable.write_text(_container_svg(rounded=False), encoding="utf-8")
    print(f"wrote {icon.relative_to(ROOT)}")
    print(f"wrote {maskable.relative_to(ROOT)}")

    for name, colour in (("logo-on-dark", PRIMARY), ("logo-on-light", PRIMARY_LIGHT)):
        out = ASSETS / f"{name}.svg"
        out.write_text(_tinted_svg(colour), encoding="utf-8")
        print(f"wrote {out.relative_to(ROOT)}")

    shutil.copyfile(LOGO, STATIC / "logo.svg")
    print(f"wrote {(STATIC / 'logo.svg').relative_to(ROOT)}")

    rasterise(icon, 32, STATIC / "favicon.png")
    for size in (192, 512):
        rasterise(icon, size, ICONS / f"icon-{size}.png")
        rasterise(maskable, size, ICONS / f"icon-maskable-{size}.png")


if __name__ == "__main__":
    main()
